language: cpp

sudo: required

dist: bionic

compiler: gcc

before_script:
    - sudo apt-get update
    - cd $TRAVIS_BUILD_DIR
    - cmake .
    - cd test
    - make

script:
    ./scripts/run.sh



