notifications:
    email: false

language: cpp

sudo: required

dist: bionic

compiler: gcc

before_script:
    - pip install --user cpp-coveralls
    - cd $TRAVIS_BUILD_DIR
    - cmake -DCOVERAGE=1 .
    - cmake --build

script:
    - tests/tests

after_success:
    - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
